[shell]
program = "/usr/bin/bash"
args = ['--login']

[cursor]
style = {shape = "Block", blinking = "Off"}

[scrolling]
history = 10000
multiplier = 3

[env]
color_prompt = "yes"

[font]
size = 12.0
[font.normal]
family = "Hack Nerd Font"
[font.bold]
family = "Hack Nerd Font"
[font.italic]
family = "Hack Nerd Font"
[font.bold_italic]
family = "Hack Nerd Font"

[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 1.0
[window.padding]
x = 2
y = 0
[window.dimensions]
columns = 90
lines = 25

[colors.normal]
black = '#0c0c0c'
red = '#c50f1f'
green = '#13a10e'
yellow = '#c19c00'
blue = '#0037da'
magenta = '#881798'
cyan = '#3a96dd'
white = '#cccccc'
[colors.primary]
background = "#cceedd"
foreground = "#000000"
[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"
[colors.bright]
black = '#767676'
red = '#e74856'
green = '#16c60c'
yellow = '#f9f1a5'
blue = '#3b78ff'
magenta = '#b4009e'
cyan = '#61d6d6'
white = '#f2f2f2'
