require("settings.common").setup()
require("settings.which_key").setup()
require("settings.lsp").setup()
require("settings.rust").setup()
require("settings.color").setup()
require("settings.nvimtree").setup()
